// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public abstract class Building extends Settlement {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private int victoryPoints;

	/**
	 * 
	 */
	public void getVictoryPoints() {
	}

	/**
	 * 
	 */
	public void upgrade() {
	}
}
