// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Abstract base for structures placed on nodes (Settlement, City).
 */
public abstract class Building {
	private final Player owner;

	public Building(Player owner) {
		this.owner = owner;
	}

	public Player getOwner() {
		return owner;
	}

	/**
	 * Victory points this building contributes.
	 */
	public abstract int getVictoryPoints();

	/**
	 * Whether this building can be upgraded (Settlement -> City).
	 */
	public abstract boolean canUpgradeToCity();
}
