// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class City {
	/**
	 * 
	 */
	private int victoryPoints = 2;

	/**
	 * 
	 * @return 
	 */
	public boolean producesDouble() {
	}
}
