// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class DiceRoller {
	/**
	 * 
	 * @param rollTwoDice 
	 */
	public void rollTwoDice(int rollTwoDice) {
	}

	/**
	 * 
	 * @param sides 
	 * @return 
	 */
	public int roll(undef sides) {
	}
}
