// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class DiceRoller {
	/**
	 * 
	 * @param rollTwoDice 
	 * @return the sum of two dice
	 */

	private final Random random;


	public int rollTwoDice(int rollTwoDice) {
		return roll(6) + roll(6);
	}

	/**
	 * 
	 * @param sides 
	 * @return 
	 */
	public int roll(int sides) {
		return random.nextInt(sides) + 1;
	}
}
