// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * An edge between two nodes A and B. Each edge can hold at most one Road.
 * Adjacency is defined by boolean logic: two edges are adjacent iff they share a node.
 */
public class Edge {
	private final int id;
	private final Node nodeA;
	private final Node nodeB;
	private Road road;

	public Edge(int id, Node nodeA, Node nodeB) {
		this.id = id;
		this.nodeA = nodeA;
		this.nodeB = nodeB;
	}

	public int getId() {
		return id;
	}

	public Node getNodeA() {
		return nodeA;
	}

	public Node getNodeB() {
		return nodeB;
	}

	public Road getRoad() {
		return road;
	}

	/**
	 * Set the road on this edge. Called when a player builds a road here.
	 */
	public void setRoad(Road road) {
		this.road = road;
	}

	/**
	 * Player who has a road on this edge, or null if none.
	 */
	public Player getOccupyingPlayer() {
		if (road == null) {
			return null;
		}
		return road.getOwner();
	}

	/**
	 * Returns true if no road is on this edge (placement rules enforced by Game/Board).
	 */
	public boolean canPlaceRoad() {
		return road == null;
	}

	/**
	 * Boolean logic: two edges are adjacent iff they share exactly one node.
	 */
	public boolean isAdjacentTo(Edge other) {
		return other != null
				&& this != other
				&& (touches(other.nodeA) || touches(other.nodeB));
	}


	/**
	 * Whether this edge touches the given node.
	 */
	public boolean touches(Node node) {
		return node != null && (node == nodeA || node == nodeB);
	}
}
