// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Node nodeA;
	/**
	 * 
	 */
	private Node nodeB;
	/**
	 * 
	 */
	private Player occupyingPlayer;
	/**
	 * 
	 */
	private Road road;

	/**
	 * 
	 * @return 
	 */
	public boolean canPlaceRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public Edge getAdjacentEdges() {
	}
}
