// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentPlayer;
	/**
	 * 
	 */
	private int roundCount;

	/**
	 * 
	 */
	private void playRound() {
	}

	/**
	 * 
	 */
	public void playTurn() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
	}

	/**
	 * 
	 */
	public void getCurrentState() {
	}
}
