// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentPlayer;
	/**
	 * 
	 */
	private int roundCount;

	public Game() {
		this.board  = new Board();
		this.players = new Player[PlayerColor.values().length];
	}

	public void intializePlayers(){
		for (int i = 0;i<players.length;i++){
			players[i] = new Player(PlayerColor.values()[i]);
		}
	}

	/**
	 * 
	 */
	private void playRound() {

	}

	/**
	 * 
	 */
	public void playTurn() {

	}

	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver(Player player) {
		if (player.getVictoryPoints() >= 10){
			return true;
		}
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
		for (Player p: players){
			if (isGameOver(p)){
				return p;
			}
		}
		return null;
	}

	/**
	 * 
	 */
	public void getCurrentState() {

	}
}