// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Board board;

	/**
	 * Gets the game board.
	 * @return the board
	 */
	public Board getBoard() {
		return board;
	}
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentPlayer;
	/**
	 * 
	 */
	private int roundCount;

	/**
	 * Dice for the game
	 */
	private Dice dice;

	/**
	 * Bank for handling payments
	 */
	private Bank bank;

	/**
	 * Validator for placement rules
	 */
	private IPlacementValidator validator;

	/**
	 * Random for player decisions
	 */
	private Random random;

	// Game constants
	private static final int VICTORY_POINTS_TO_WIN = 10;
	private static final int MAX_RESOURCES_BEFORE_BUILD = 7;
	private static final int DICE_SIDES = 6;
	private static final int TOTAL_NODES = 54;

	/**
	 * Constructor with dependency injection.
	 */
	public Game(Board board, Dice dice, Bank bank, IPlacementValidator validator, int numPlayers) {
		this.board = board;
		this.dice = dice;
		this.bank = bank;
		this.validator = validator;
		this.players = new Player[numPlayers];
		this.random = new Random();
		this.currentPlayer = 0;
		this.roundCount = 0;
		
		// Initialize players
		initializePlayers();
	}

	public void initializePlayers(){

		// Initialize all players with their colors
		for (int i = 0; i < players.length; i++){
			players[i] = new Player(PlayerColor.values()[i]);
		}

		// All players initialized successfully
	}

	/**
	 * Setup phase: each player places 2 settlements and 2 roads in one go.
	 */
	public void setupInitialSettlements() {

		for (int i = 0; i < players.length; i++) {
			Player player = players[i];
			System.out.println("\n=== " + player.getColor() + " Player Setup ===");

			// Place first settlement
			placeSettlement(player, i, 1);
			
			// Place first road
			placeRoad(player, i, 1);
			
			// Place second settlement
			placeSettlement(player, i, 2);
			
			// Place second road
			placeRoad(player, i, 2);

		}
	}

	/**
	 * Places one settlement for a player during setup (random choice).
	 */
	private void placeSettlement(Player player, int playerIndex, int settlementNumber) {

		// Get all available nodes (following distance rule)
		List<Integer> availableNodes = getAvailableSettlementNodes();
		
		if (availableNodes.isEmpty()) {
			System.out.println(player.getColor() + " - No available nodes for settlement #" + settlementNumber);
			return;
		}
		
		// Choose randomly
		int nodeId = availableNodes.get(random.nextInt(availableNodes.size()));
		Node node = board.getNode(nodeId);
		
		if (node != null && placeSettlementSetup(node, player)) {
			System.out.println(roundCount + " / " + player.getColor() + ": Placed settlement #" + settlementNumber + " on node " + nodeId);
		}

	}

	/**
	 * Places one road for a player during setup (random choice).
	 */
	private void placeRoad(Player player, int playerIndex, int roadNumber) {

		// Get all nodes the player occupies
		List<Integer> occupiedNodes = getOccupiedNodeIds(player);
		
		if (occupiedNodes.isEmpty()) {
			System.out.println(player.getColor() + " - No settlements to build roads from");
			return;
		}
		
		// Choose random starting node
		int firstNodeId = occupiedNodes.get(random.nextInt(occupiedNodes.size()));
		
		// Get adjacent unoccupied nodes
		List<Integer> adjacentUnoccupied = getAdjacentUnoccupiedNodeIds(firstNodeId);
		
		if (adjacentUnoccupied.isEmpty()) {

			// Try another occupied node
			for (int occupiedId : occupiedNodes) {
				if (occupiedId != firstNodeId) {
					adjacentUnoccupied = getAdjacentUnoccupiedNodeIds(occupiedId);
					if (!adjacentUnoccupied.isEmpty()) {
						firstNodeId = occupiedId;
						break;
					}
				}
			}
		}
		
		if (adjacentUnoccupied.isEmpty()) {
			System.out.println(player.getColor() + " - No available adjacent nodes for road #" + roadNumber);
			return;
		}
		
		// Choose random destination node
		int secondNodeId = adjacentUnoccupied.get(random.nextInt(adjacentUnoccupied.size()));
		
		// Find the edge between the two nodes
		Edge edge = board.findEdge(firstNodeId, secondNodeId);
		if (edge != null && placeRoadSetup(edge, player)) {
			System.out.println(roundCount + " / " + player.getColor() + ": Placed road #" + roadNumber + " from node " + firstNodeId + " to node " + secondNodeId);
		}

	}

	/**
	 * Starts the game. First sets up initial settlements, then runs the game loop.
	 */
	public void startGame() {
		startGame(Integer.MAX_VALUE);
	}

	/**
	 * Starts the game with a maximum round limit.
	 * @param maxRounds maximum number of rounds to play
	 */
	public void startGame(int maxRounds) {
		setupInitialSettlements();
		
		System.out.println("\n=== GAME START ===");
		
		// Game loop - continue until someone wins or max rounds reached
		while (getWinner() == null) {
			// Check if we've reached max rounds before starting this round
			if (roundCount >= maxRounds) {
				System.out.println("\n=== GAME OVER ===");
				System.out.println("Maximum rounds (" + maxRounds + ") reached!");
				// Find player with most victory points
				Player winner = players[0];
				for (int i = 1; i < players.length; i++) {
					if (players[i].getVictoryPoints() > winner.getVictoryPoints()) {
						winner = players[i];
					}
				}
				System.out.println(winner.getColor() + " Player wins with " + winner.getVictoryPoints() + " victory points!");
				return;
			}
			
			// Process each player's turn in this round
			for (int i = 0; i < players.length; i++) {
				currentPlayer = i;
				Player player = players[i];
				
				// Check for winner before each turn
				if (getWinner() != null) {
					break;
				}
				
				System.out.println("\n--- " + player.getColor() + " Player's Turn ---");
				
				// Roll dice for this turn
				int diceRoll = dice.rollTwoDice(DICE_SIDES);
				System.out.println("Dice roll: " + diceRoll);
				
		// Distribute resources to all players
		distributeResources(diceRoll);
		
		// Player actions - build or pass
		playerTurn(player, i);
		
		// End of turn processing
			}
			
			// Print victory points at end of round (R1.7 requirement)
			System.out.println("\n=== End of Round " + roundCount + " - Victory Points ===");
			for (int i = 0; i < players.length; i++) {
				System.out.println(players[i].getColor() + " Player: " + players[i].getVictoryPoints() + " VP");
			}
			System.out.println();
			
			// Increment round counter after all players have taken their turn
			roundCount++;
		}
		
		// Game over - determine winner
		Player winner = getWinner();
		if (winner != null) {
			System.out.println("\n=== GAME OVER ===");
			System.out.println(winner.getColor() + " Player wins with " + winner.getVictoryPoints() + " victory points!");
		}
	}

	/**
	 * Handles a player's turn - they choose randomly from available actions.
	 */
	private void playerTurn(Player player, int playerIndex) {

		// Count total resources
		int totalResources = getTotalResourceCount(player);
		
		// If player has 7+ resources, must build something
		boolean mustBuild = totalResources >= MAX_RESOURCES_BEFORE_BUILD;
		
		// Get available actions
		List<String> availableActions = getAvailableActions(player, mustBuild);
		
		if (availableActions.isEmpty()) {
			System.out.println(player.getColor() + " - No available actions");
			return;
		}
		
		// Choose randomly
		String action = availableActions.get(random.nextInt(availableActions.size()));
		
		switch (action) {
			case "SETTLEMENT":
				buildSettlement(player, playerIndex);
				break;
			case "CITY":
				buildCity(player, playerIndex);
				break;
			case "ROAD":
				buildRoad(player, playerIndex);
				break;
			case "PASS":
				System.out.println(roundCount + " / " + player.getColor() + ": Pass");
				break;
		}

	}

	/**
	 * Gets available actions for a player.
	 */
	private List<String> getAvailableActions(Player player, boolean mustBuild) {

		List<String> actions = new ArrayList<>();
		
		// Check if can build settlement
		if (player.canBuildSettlement() && !getAvailableSettlementNodesForPlayer(player).isEmpty()) {
			actions.add("SETTLEMENT");
		}
		
		// Check if can build city
		if (player.canBuildCity() && !getUpgradeableCityNodes(player).isEmpty()) {
			actions.add("CITY");
		}
		
		// Check if can build road
		if (player.canBuildRoad() && !getAvailableRoadEdgesForPlayer(player).isEmpty()) {
			actions.add("ROAD");
		}
		
		// Can pass only if not forced to build
		if (!mustBuild) {
			actions.add("PASS");
		}
		
		return actions;

	}

	/**
	 * Player builds a settlement (random choice).
	 */
	private void buildSettlement(Player player, int playerIndex) {

		List<Integer> availableNodes = getAvailableSettlementNodesForPlayer(player);
		
		if (availableNodes.isEmpty()) {
			System.out.println(player.getColor() + " - Cannot build settlement (no valid locations)");
			return;
		}
		
		int nodeId = availableNodes.get(random.nextInt(availableNodes.size()));
		Node node = board.getNode(nodeId);
		
		if (node != null && placeSettlement(node, player)) {
			System.out.println(roundCount + " / " + player.getColor() + ": Built settlement on node " + nodeId);
		} else {
			System.out.println(roundCount + " / " + player.getColor() + ": Failed to build settlement");
		}

	}

	/**
	 * Player builds a city (random choice).
	 */
	private void buildCity(Player player, int playerIndex) {

		List<Integer> upgradeableNodes = getUpgradeableCityNodes(player);
		
		if (upgradeableNodes.isEmpty()) {
			System.out.println(player.getColor() + " - Cannot build city (no settlements to upgrade)");
			return;
		}
		
		int nodeId = upgradeableNodes.get(random.nextInt(upgradeableNodes.size()));
		Node node = board.getNode(nodeId);
		
		if (node != null && placeCity(node, player)) {
			System.out.println(roundCount + " / " + player.getColor() + ": Built city on node " + nodeId);
		} else {
			System.out.println(roundCount + " / " + player.getColor() + ": Failed to build city");
		}

	}

	/**
	 * Player builds a road (random choice).
	 */
	private void buildRoad(Player player, int playerIndex) {

		List<Edge> availableEdges = getAvailableRoadEdgesForPlayer(player);
		
		if (availableEdges.isEmpty()) {
			System.out.println(player.getColor() + " - Cannot build road (no valid locations)");
			return;
		}
		
		Edge edge = availableEdges.get(random.nextInt(availableEdges.size()));
		
		if (placeRoad(edge, player)) {
			System.out.println(roundCount + " / " + player.getColor() + ": Built road on edge " + edge.getId());
		} else {
			System.out.println(roundCount + " / " + player.getColor() + ": Failed to build road");
		}

	}

	/**
	 * Gets total resource count for a player.
	 */
	private int getTotalResourceCount(Player player) {
		return player.getTotalResourceCount();
	}

	/**
	 * Distributes resources to all players based on the dice roll.
	 * Each player with a settlement/city on a tile matching the rolled number receives resources.
	 * Cities produce double resources.
	 */
	private void distributeResources(int diceRoll) {

		// Skip 7 (robber - no resources distributed)
		if (diceRoll == 7) {
			return;
		}
		
		// Process all tiles on the board
		for (Tile tile : board.getTiles()) {
			if (tile.getNumber() == diceRoll) {
				ResourceType resource = tile.produceResource();
				if (resource == ResourceType.NULL) continue;
				
				int[] nodeIds = tile.getNodeIds();
				for (int nodeId : nodeIds) {
					Node node = board.getNode(nodeId);
					if (node != null && node.isOccupied()) {
						Player owner = node.getOccupyingPlayer();
						if (owner != null) {

							// Use resource multiplier from building
							int amount = node.getBuilding().getResourceMultiplier();
							for (int i = 0; i < amount; i++) {
								owner.addResource(resource);
							}
							if (amount > 1) {
								System.out.println(roundCount + " / " + owner.getColor() + ": Received 2x " + resource);
							} else {
								System.out.println(roundCount + " / " + owner.getColor() + ": Received " + resource);
							}
						}
					}
				}
			}
		}

	}

	/**
	 * Gets all available nodes for settlement placement (setup phase - distance rule only).
	 */
	private List<Integer> getAvailableSettlementNodes() {
		List<Integer> available = new ArrayList<>();
		
		for (int i = 0; i < TOTAL_NODES; i++) {
			Node node = board.getNode(i);
			if (node != null && node.canPlaceBuilding()) {
				available.add(i);
			}
		}
		
		return available;
	}

	/**
	 * Gets available settlement nodes for a player during normal play (must be connected by road).
	 */
	private List<Integer> getAvailableSettlementNodesForPlayer(Player player) {

		List<Integer> available = new ArrayList<>();
		
		for (int i = 0; i < TOTAL_NODES; i++) {
			Node node = board.getNode(i);
			if (node != null && validator.canPlaceSettlement(node, player, false) && player.canBuildSettlement()) {

				// Check if player has a road leading to this node
				boolean hasRoadConnection = false;
				for (Edge edge : board.getEdges()) {
					if (edge != null && edge.touches(node) && edge.getRoad() != null && edge.getRoad().getOwner() == player) {
						hasRoadConnection = true;
						break;
					}
				}
				if (hasRoadConnection) {
					available.add(i);
				}
			}
		}
		
		return available;

	}

	/**
	 * Gets nodes where player can upgrade settlement to city.
	 */
	private List<Integer> getUpgradeableCityNodes(Player player) {

		List<Integer> upgradeable = new ArrayList<>();
		
		for (int i = 0; i < TOTAL_NODES; i++) {
			Node node = board.getNode(i);
			if (node != null && validator.canPlaceCity(node, player) && player.canBuildCity()) {
				upgradeable.add(i);
			}
		}
		
		return upgradeable;

	}

	/**
	 * Gets available road edges for a player (connected to their roads/settlements).
	 */
	private List<Edge> getAvailableRoadEdgesForPlayer(Player player) {

		List<Edge> available = new ArrayList<>();
		
		// Get all edges that can be reached from player's buildings or roads
		for (Edge edge : board.getEdges()) {
			if (edge != null && edge.canPlaceRoad() && player.canBuildRoad()) {
				Node nodeA = edge.getNodeA();
				Node nodeB = edge.getNodeB();
				
				// Check if edge is adjacent to player's building
				boolean adjacentToBuilding = (nodeA.isOccupied() && nodeA.getOccupyingPlayer() == player) ||
											(nodeB.isOccupied() && nodeB.getOccupyingPlayer() == player);
				
				// Check if edge is adjacent to player's road
				boolean adjacentToRoad = false;
				for (Edge otherEdge : board.getEdges()) {
					if (otherEdge != null && otherEdge != edge && otherEdge.getRoad() != null && 
						otherEdge.getRoad().getOwner() == player) {
						if (edge.touches(otherEdge.getNodeA()) || edge.touches(otherEdge.getNodeB())) {
							adjacentToRoad = true;
							break;
						}
					}
				}
				
				if (adjacentToBuilding || adjacentToRoad) {
					available.add(edge);
				}
			}
		}
		
		return available;

	}

	/**
	 * Gets the index of a player in the players array.
	 * @param player the player to find
	 * @return the index of the player, or -1 if not found
	 */
	private int getPlayerNumber(Player player) {
		for (int i = 0; i < players.length; i++) {
			if (players[i] == player) {
				return i;
			}
		}
		return -1;
	}

	/**
	 * Gets all node IDs that the player currently occupies (settlements/cities).
	 * @param player the player
	 * @return list of occupied node IDs
	 */
	private List<Integer> getOccupiedNodeIds(Player player) {

		List<Integer> occupied = new ArrayList<>();
		
		for (int i = 0; i < TOTAL_NODES; i++) {
			Node node = board.getNode(i);
			if (node != null && node.isOccupied() && node.getOccupyingPlayer() == player) {
				occupied.add(i);
			}
		}
		
		return occupied;

	}

	/**
	 * Gets all node IDs adjacent to the given node that are NOT occupied.
	 * @param nodeId the node to find adjacent unoccupied nodes for
	 * @return list of adjacent unoccupied node IDs
	 */
	private List<Integer> getAdjacentUnoccupiedNodeIds(int nodeId) {

		List<Integer> adjacent = new ArrayList<>();
		Node node = board.getNode(nodeId);
		if (node == null) {
			return adjacent;
		}
		
		// Check all edges to find adjacent nodes
		for (Edge edge : board.getEdges()) {
			if (edge != null && edge.touches(node)) {
				Node otherNode = (edge.getNodeA() == node) ? edge.getNodeB() : edge.getNodeA();

				// Only include if not occupied
				if (!otherNode.isOccupied()) {
					int otherId = otherNode.getId();
					if (!adjacent.contains(otherId)) {
						adjacent.add(otherId);
					}
				}
			}
		}
		
		return adjacent;

	}

	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver(Player player) {
		if (player.getVictoryPoints() >= VICTORY_POINTS_TO_WIN){
			return true;
		}
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
		for (Player p: players){
			if (isGameOver(p)){
				return p;
			}
		}
		return null;
	}

	/**
	 * Orchestrates settlement placement during setup (no resource cost).
	 * GRASP: Controller - Game orchestrates the full placement flow.
	 */
	private boolean placeSettlementSetup(Node node, Player player) {
		// 1. Validate placement rules
		if (!validator.canPlaceSettlement(node, player, true)) {
			return false;
		}

		// 2. Use settlement piece (no resources paid during setup)
		if (!bank.useSettlementPieceSetup(player)) {
			return false;
		}

		// 3. Update node state
		node.setBuilding(new Settlement(player));
		node.setOccupyingPlayer(player);

		// 4. Add victory point
		player.addVictoryPoint(1);

		return true;
	}

	/**
	 * Orchestrates settlement placement during normal play.
	 * GRASP: Controller - Game orchestrates the full placement flow.
	 */
	private boolean placeSettlement(Node node, Player player) {
		// 1. Validate placement rules
		if (!validator.canPlaceSettlement(node, player, false)) {
			return false;
		}

		// Check road connectivity (normal play requirement)
		boolean hasRoadConnection = false;
		for (Edge edge : board.getEdges()) {
			if (edge != null && edge.touches(node) && edge.getRoad() != null && edge.getRoad().getOwner() == player) {
				hasRoadConnection = true;
				break;
			}
		}
		if (!hasRoadConnection) {
			return false;
		}

		// 2. Pay for settlement
		if (!bank.payForSettlement(player)) {
			return false;
		}

		// 3. Update node state
		node.setBuilding(new Settlement(player));
		node.setOccupyingPlayer(player);

		return true;
	}

	/**
	 * Orchestrates city placement (upgrade settlement).
	 * GRASP: Controller - Game orchestrates the full placement flow.
	 */
	private boolean placeCity(Node node, Player player) {
		// 1. Validate placement rules
		if (!validator.canPlaceCity(node, player)) {
			return false;
		}

		// 2. Pay for city
		if (!bank.payForCity(player)) {
			return false;
		}

		// 3. Update node state (upgrade settlement to city)
		node.setBuilding(new City(player));
		node.setOccupyingPlayer(player);

		return true;
	}

	/**
	 * Orchestrates road placement during setup (no resource cost).
	 * GRASP: Controller - Game orchestrates the full placement flow.
	 */
	private boolean placeRoadSetup(Edge edge, Player player) {
		// 1. Validate placement rules
		if (!validator.canPlaceRoad(edge, player, true)) {
			return false;
		}

		// 2. Use road piece (no resources paid during setup)
		if (!bank.useRoadPieceSetup(player)) {
			return false;
		}

		// 3. Update edge state
		edge.setRoad(new Road(player, edge));

		return true;
	}

	/**
	 * Orchestrates road placement during normal play.
	 * GRASP: Controller - Game orchestrates the full placement flow.
	 */
	private boolean placeRoad(Edge edge, Player player) {
		// 1. Validate placement rules
		if (!validator.canPlaceRoad(edge, player, false)) {
			return false;
		}

		// Check connectivity (must be adjacent to player's building or road)
		Node nodeA = edge.getNodeA();
		Node nodeB = edge.getNodeB();
		boolean adjacentToBuilding = (nodeA.isOccupied() && nodeA.getOccupyingPlayer() == player) ||
									(nodeB.isOccupied() && nodeB.getOccupyingPlayer() == player);

		boolean adjacentToRoad = false;
		for (Edge otherEdge : board.getEdges()) {
			if (otherEdge != null && otherEdge != edge && otherEdge.getRoad() != null &&
				otherEdge.getRoad().getOwner() == player) {
				if (edge.touches(otherEdge.getNodeA()) || edge.touches(otherEdge.getNodeB())) {
					adjacentToRoad = true;
					break;
				}
			}
		}

		if (!adjacentToBuilding && !adjacentToRoad) {
			return false;
		}

		// 2. Pay for road
		if (!bank.payForRoad(player)) {
			return false;
		}

		// 3. Update edge state
		edge.setRoad(new Road(player, edge));

		return true;
	}
}
