// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Player occupyingPlayer;

	/**
	 * 
	 * @return 
	 */
	public boolean canPlaceBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getAdjacentNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getAdjacentTiles() {
	}
}
