// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * A vertex between tiles on the board where a settlement/city can be built.
 */
public class Node {
	private final int id;
	private Building building;
	/**
	 * 
	 */
	private Player occupyingPlayer;

	/**
	 * 
	 * @return 
	 */
	public boolean canPlaceBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getAdjacentNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getAdjacentTiles() {
	}
}
