// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private undef color;
	/**
	 * 
	 */
	private EMap resources;
	/**
	 * 
	 */
	private Settlement Settlements;
	/**
	 * 
	 */
	private City cities;
	/**
	 * 
	 */
	private Road roads;
	/**
	 * 
	 */
	private int victoryPoints;

	/**
	 * 
	 * @param res 
	 */
	public void addResource(undef res) {
	}

	/**
	 * 
	 * @param res 
	 * @return 
	 */
	public boolean removeResource(boolean res) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildSettlement() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canBuildCity() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}
}
