// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Player colors in Catan (typically 4 players).
 */
public enum PlayerColor {
	RED,
	BLUE,
	WHITE,
	ORANGE
}