// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class ResourceCard {
	/**
	 * 
	 */
	private undef type;

	/**
	 * 
	 * @return 
	 */
	public void getType() {
	}
}
