// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Resource types in Catan (produced by terrain tiles).
 */
public enum ResourceType {
	WOOD,
	BRICK,
	SHEEP,
	WHEAT,
	ORE,
	NULL
}
