// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * A resource card held by a player (type is one of the five resources).
 */
public class ResourceCard extends Tile{
	private final ResourceType type;

	public ResourceCard(ResourceType type) {
		this.type = type;
	}

	public ResourceType getType() {
		return type;
	}

	
}
