// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Resource types in Catan (produced by terrain tiles).
 */
public enum ResourceType {
	WOOD,
	SHEEP,
	WHEAT,
	BRICK,
	ORE,
	NULL  // No resource (e.g. desert)
}
