// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * A road placed on an edge; owned by a player. Used for longest road calculation.
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Edge edge;

	/**
	 * 
	 * @return 
	 */
	public int getLongestRoadCount() {
	}
}
