// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/************************************************************/
/**
 * 
 */
public class Settlement {
	/**
	 * 
	 */
	private int victoryPoints = 1;

	/**
	 * 
	 * @return 
	 */
	public boolean canUpgradeToCity() {
	}
}
