// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Terrain types for board tiles. Desert produces no resource.
 */
public enum TerrainType {
	FOREST,
	PASTURE,
	FIELDS,
	HILLS,
	MOUNTAINS,
	DESERT
}
