// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Terrain types for board tiles. Desert produces no resource.
 */
public enum TerrainType {
	WOOD,
	BRICK,
	SHEEP,
	WHEAT,
	ORE,
	DESERT
}
