// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * A hex tile on the board. Produces a resource when corresponding number is rolled (except Desert).
 */
public class Tile {
	private final int q;
	private final int s;
	private final int r;
	private final TerrainType terrain;
	private final int number;  // dice number 2-12 (0 for desert)
	private final int[] nodeIds;  // IDs of the 6 nodes that touch this tile

	public Tile(int q, int s, int r, TerrainType terrain, int number, int[] nodeIds) {
		this.q = q;
		this.s = s;
		this.r = r;
		this.terrain = terrain;
		this.number = number;
		this.nodeIds = nodeIds;  // Store the node IDs directly
	}

	public int getQ(){
		return q;
	}
	public int getS(){
		return s;
	}
	public int getR(){
		return r;
	}
	public TerrainType getTerrain(){
		return terrain;
	}
	public int getNumber(){
		return number;
	}
	/**
	 * Returns the array of node IDs (0-53) that touch this tile.
	 * To get the actual Node objects, use Board.getNode(id) for each ID.
	 */
	public int[] getNodeIds(){
		return nodeIds;
	}

	/**
	 * Produce resource for adjacent settlements/cities when this number is rolled.
	 * Desert produces nothing
	 */
	public ResourceType produceResource(){
		switch(terrain){
		  case FOREST: 
			  return ResourceType.WOOD;
		  case PASTURE:
			  return ResourceType.SHEEP;
		  case FIELDS:
			  return ResourceType.WHEAT;
		  case HILLS:
			  return ResourceType.BRICK;
		  case MOUNTAINS:
			  return ResourceType.ORE;
		  case DESERT:
			  return ResourceType.NULL;
		}
	  }
}
