// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.ArrayList;

/**
 * A hex tile on the board. Produces a resource when corresponding number is rolled (except Desert).
 */
public class Tile {
	private final int q;
	private final int s;
	private final int r;
	private final TerrainType terrain;
	private final int number;  // dice number 2-12 (0 for desert)
	private final Node[] nodes = new ArrayList<Node>(6);
	// private final Node[] nodes;
	// private final Edge[] edges;

	public Tile(int q, int s, int r, TerrainType terrain, int number,int[] nodeIds) {
		this.q = q;
		this.s = s;
		this.r = r;
		this.terrain = terrain;
		this.number = number;

		for (int i = 0; i<=5; i++){
			nodes[i] = new Node(nodeIds[i]);
		}
	}

	public int getQ(){
		return q;
	}
	public int getS(){
		return s;
	}
	public int getR(){
		return r;
	}
	public TerrainType getTerrain(){
		return terrain;
	}
	public int getNumber(){
		return number;
	}
	public Node[] getNodes(){
		return nodes;
	}
	public Edge[] getEdges(){
		return edges;
	}

	/**
	 * Produce resource for adjacent settlements/cities when this number is rolled.
	 * Desert produces nothing
	 */
	public ResourceType produceResource(){
		switch(terrain){
		  case FOREST: 
			  return ResourceType.WOOD;
		  case PASTURE:
			  return ResourceType.SHEEP;
		  case FIELDS:
			  return ResourceType.WHEAT;
		  case HILLS:
			  return ResourceType.BRICK;
		  case MOUNTAINS:
			  return ResourceType.ORE;
		  case DESERT:
			  return ResourceType.NULL;
		}
	  }
}
