// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.Arrays;
import java.util.Map;

/**
 * A hex tile on the board. Produces a resource when corresponding number is rolled (except Desert).
 */
public class Tile {
	private static final Map<TerrainType, ResourceType> TERRAIN_TO_RESOURCE = Map.of(
		TerrainType.FOREST, ResourceType.WOOD,
		TerrainType.PASTURE, ResourceType.SHEEP,
		TerrainType.FIELDS, ResourceType.WHEAT,
		TerrainType.HILLS, ResourceType.BRICK,
		TerrainType.MOUNTAINS, ResourceType.ORE,
		TerrainType.DESERT, ResourceType.NULL
	);
	private final int q;
	private final int s;
	private final int r;
	private final TerrainType terrain;
	private final int number;  // dice number 2-12 (0 for desert)
	private final int[] nodeIds;  // IDs of the 6 nodes that touch this tile

	public Tile(int q, int s, int r, TerrainType terrain, int number, int[] nodeIds) {
		// Initialize tile coordinates
		this.q = q;
		this.s = s;
		this.r = r;
		
		// Initialize tile properties
		this.terrain = terrain;
		this.number = number;
		this.nodeIds = nodeIds;  // Store the node IDs directly
		// Tile initialization complete
	}

	public int getQ(){
		return q;
	}

	public int getS(){
		return s;
	}

	public int getR(){
		return r;
	}

	public TerrainType getTerrain(){
		return terrain;
	}

	public int getNumber(){
		return number;
	}
	/**
	 * Returns the array of node IDs (0-53) that touch this tile.
	 * To get the actual Node objects, use Board.getNode(id) for each ID.
	 * Returns a defensive copy to prevent mutation.
	 */
	public int[] getNodeIds(){
		return Arrays.copyOf(nodeIds, nodeIds.length);
	}

	/**
	 * Produce resource for adjacent settlements/cities when this number is rolled.
	 * Desert produces nothing
	 */
	public ResourceType produceResource(){
		// Look up resource type from terrain
		return TERRAIN_TO_RESOURCE.getOrDefault(terrain, ResourceType.NULL);
	}
}
