// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Abstract base class for buildings placed on nodes.
 * Generalizes Settlement and City as defined in the UML.
 *
 * UML: abstract Building with attributes owner, victoryPoints.
 *       Operations: getVictoryPoints(), upgrade().
 */
public abstract class Building {

    private final Player owner;
    private final int victoryPoints;

    protected Building(Player owner, int victoryPoints) {
        this.owner = owner;
        this.victoryPoints = victoryPoints;
    }

    public int getVictoryPoints() {
        return victoryPoints;
    }

    public Player getOwner() {
        return owner;
    }

    /**
     * Returns the number of resource cards produced per adjacent tile yield.
     * Settlements produce 1; cities produce 2.
     */
    public abstract int getResourceMultiplier();

    /**
     * Upgrade hook. Subclasses define whether they can be upgraded.
     */
    public abstract boolean canUpgrade();

    @Override
    public String toString() {
        return String.format("%s (owner=%s, VP=%d)",
                getClass().getSimpleName(), owner.getColor(), victoryPoints);
    }
}
