// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Represents a city in Catan.
 * Worth 2 victory points. Produces 2 resource cards per adjacent producing tile.
 * Cannot be upgraded further.
 *
 * UML: City with victoryPoints = 2.
 *       Operation: producesDouble().
 *       Generalization: Building → City.
 */
public class City extends Building {

    private static final int VICTORY_POINTS = 2;

    public City(Player owner) {
        super(owner, VICTORY_POINTS);
    }

    @Override
    public int getResourceMultiplier() {
        return 2;
    }

    /**
     * Cities always produce double the resources of a settlement.
     * @return true
     */
    public boolean producesDouble() {
        return true;
    }

    /**
     * Cities cannot be further upgraded.
     * @return false
     */
    @Override
    public boolean canUpgrade() {
        return false;
    }
}
