// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Types of development cards in Catan.
 * Knight (14), Road Building (2), Year of Plenty (2), Monopoly (2), Victory Point (5).
 */
public enum DevelopmentCardType {
	KNIGHT,
	ROAD_BUILDING,
	YEAR_OF_PLENTY,
	MONOPOLY,
	VICTORY_POINT
}
