// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Represents a development card in Catan.
 * Three categories: Knight (14), Progress (6), Victory Point (5) = 25 total.
 * Cards cannot be traded. Only 1 non-VP card may be played per turn,
 * and not on the same turn it was bought (VP cards are the exception).
 */
public class DevelopmentCard {

    private final DevelopmentCardType type;
    private final String name;
    private boolean played;
    private int turnBought;

    public DevelopmentCard(DevelopmentCardType type, String name) {
        this.type = type;
        this.name = name;
        this.played = false;
        this.turnBought = -1;
    }

    /**
     * Checks whether this card can be played on the given turn.
     * Rules: cannot play a card bought this turn (except VP cards).
     * @param currentTurn the current turn number
     * @return true if the card is eligible to be played
     */
    public boolean canPlay(int currentTurn) {
        if (played) return false;
        if (type == DevelopmentCardType.VICTORY_POINT) return true;
        return turnBought < currentTurn;
    }

    // ========== Getters / Setters ==========

    public DevelopmentCardType getType() { return type; }
    public String getName()             { return name; }
    public boolean isPlayed()           { return played; }
    public void setPlayed(boolean v)    { this.played = v; }
    public int getTurnBought()          { return turnBought; }
    public void setTurnBought(int t)    { this.turnBought = t; }

    @Override
    public String toString() {
        return String.format("%s (%s)", name, type);
    }
}
