// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.Random;

/**
 * Handles all dice rolling operations for the game.
 * Uses two standard six-sided dice as per Catan rules.
 */
public class DiceRoller {

    private final Random random;
    private int lastDie1;
    private int lastDie2;

    public DiceRoller() {
        this.random = new Random();
    }

    public DiceRoller(long seed) {
        this.random = new Random(seed);
    }

    /**
     * Rolls a single die with the given number of sides.
     * @param sides number of sides on the die
     * @return result of the roll (1 to sides inclusive)
     */
    public int roll(int sides) {
        return random.nextInt(sides) + 1;
    }

    /**
     * Rolls two six-sided dice and returns their sum (2–12).
     * @return sum of two dice
     */
    public int rollTwoDice() {
        lastDie1 = roll(6);
        lastDie2 = roll(6);
        return lastDie1 + lastDie2;
    }

    public int getLastDie1() {
        return lastDie1;
    }

    public int getLastDie2() {
        return lastDie2;
    }

    public int getLastTotal() {
        return lastDie1 + lastDie2;
    }
}
