// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Entry point for the Settlers of Catan simulator.
 * Runs a complete game with 4 bot players and prints a full action trace.
 *
 * Usage:  java SettlersOfCatan.Main [seed]
 *   seed — optional long for reproducible games
 */
public class Main {

    public static void main(String[] args) {
        long seed;
        if (args.length > 0) {
            try {
                seed = Long.parseLong(args[0]);
            } catch (NumberFormatException e) {
                seed = System.currentTimeMillis();
            }
        } else {
            seed = System.currentTimeMillis();
        }
        System.out.println("Seed: " + seed + "\n");

        Game game = new Game(seed);
        game.initialize();
        game.play();

        // Summary
        System.out.println("\n=== TRACE SUMMARY ===");
        System.out.println("Trace entries : " + game.getGameTrace().size());
        System.out.println("Rounds        : " + game.getRoundCount());
        System.out.println("Turns         : " + game.getTurnCount());
        if (game.getWinner() != null) {
            System.out.println("Winner        : " + game.getWinner().getColor()
                    + " (" + game.getWinner().getVictoryPoints() + " VP)");
        } else {
            System.out.println("No winner (max rounds reached).");
        }
    }
}
