// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Represents a resource card in Catan.
 * Each card has a ResourceType (WOOD, BRICK, SHEEP, WHEAT, ORE).
 */
public class ResourceCard {

    private final ResourceType type;

    public ResourceCard(ResourceType type) {
        this.type = type;
    }

    public ResourceType getType() {
        return type;
    }

    @Override
    public String toString() {
        return type.name();
    }
}
