// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

import java.util.HashSet;
import java.util.Set;

/**
 * Represents a road in Catan.
 * Placed on edges, connecting settlements and cities.
 * The longest continuous road of 5+ segments earns 2 victory points.
 *
 * UML: Road with attributes owner, edge.
 *       Operation: getLongestRoadCount().
 */
public class Road {

    private final Player owner;
    private final Edge edge;

    public Road(Player owner, Edge edge) {
        this.owner = owner;
        this.edge = edge;
    }

    /**
     * Calculates the longest continuous road segment that passes through this road.
     * Uses DFS in both directions from this edge, respecting opponent-building blockades.
     * @return the longest road count through this edge
     */
    public int getLongestRoadCount() {
        Set<Edge> visited = new HashSet<>();
        visited.add(edge);
        int fromA = dfs(edge.getNodeA(), visited);
        int fromB = dfs(edge.getNodeB(), visited);
        return 1 + fromA + fromB;
    }

    /**
     * DFS helper: explores road length from a given node.
     * Stops if an opponent's building blocks the path.
     */
    private int dfs(Node node, Set<Edge> visited) {
        // Opponent building on node blocks continuation
        if (node.getOccupyingPlayer() != null
                && !node.getOccupyingPlayer().equals(owner)) {
            return 0;
        }

        int max = 0;
        for (Edge e : node.getEdges()) {
            if (!visited.contains(e)
                    && e.getRoad() != null
                    && e.getRoad().getOwner().equals(owner)) {
                visited.add(e);
                Node next = e.getOtherNode(node);
                int length = 1 + dfs(next, visited);
                max = Math.max(max, length);
                visited.remove(e); // backtrack
            }
        }
        return max;
    }

    public Player getOwner() { return owner; }
    public Edge getEdge()    { return edge; }

    @Override
    public String toString() {
        return String.format("Road(owner=%s, edge=%d)", owner.getColor(), edge.getId());
    }
}
