// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SettlersOfCatan;

/**
 * Represents a settlement in Catan.
 * Worth 1 victory point. Produces 1 resource card per adjacent producing tile.
 * Can be upgraded to a City.
 *
 * UML: Settlement with victoryPoints = 1.
 *       Operation: canUpgradeToCity().
 *       Generalization: Building → Settlement.
 */
public class Settlement extends Building {

    private static final int VICTORY_POINTS = 1;

    public Settlement(Player owner) {
        super(owner, VICTORY_POINTS);
    }

    @Override
    public int getResourceMultiplier() {
        return 1;
    }

    @Override
    public boolean canUpgrade() {
        return true;
    }

    /**
     * Checks if the owner has enough resources to upgrade this settlement to a city.
     * Requires: 3 ORE + 2 WHEAT.
     * @return true if the owner can afford the upgrade
     */
    public boolean canUpgradeToCity() {
        return getOwner().canBuildCity();
    }
}
